### ISSUE TITLE
cycle keyword didn't seem to work in template

### ISSUE THREAD

**Issue by jabooth** [menpo/landmarker.io#107]
For some reason I couldn't get the `cycle` keyword to work as specified here:
https://github.com/menpo/landmarker.io/wiki/Templates-specification

I ended up performing the substitution suggested, e.g.:
```
- 0:4
- 4 1
```
did we have a test for this @lirsacc? Sorry this is a brief issue, just cropped up and wanted to record it!

here's the file I was attempting:
```yaml
groups:
-   label: n_prn
    points: 2
    connectivity: 0:1
-   label: acR_sbalR_sn_sbalL_acL
    points: 5
    connectivity: 0:4
-   label: eyeL_en_pi_ex_ps
    points: 4
    connectivity: cycle
-   label: eyeR_en_pi_ex_ps
    points: 4
    connectivity: cycle
-   label: ls_cphL_chL_li_chR_cphR
    points: 6
    connectivity: cycle
-   label: stoU_stoL
    points: 2
-   label: sl_gn
    points: 2
    connectivity: 0:1
-   label: earL_t_sa_xx_sba
    points: 4
    connectivity: cycle
-   label: earR_t_sa_xx_sba
    points: 4
    connectivity: cycle

```
